# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QSlider
from pyqtgraph import PlotWidget, plot




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 520)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("QMainWindow {background: '#32CC99';}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.columnView_2 = QtWidgets.QColumnView(self.centralwidget)
        self.columnView_2.setGeometry(QtCore.QRect(20, 260, 311, 241))
        self.columnView_2.setObjectName("columnView_2")
        self.columnView_3 = QtWidgets.QColumnView(self.centralwidget)
        self.columnView_3.setGeometry(QtCore.QRect(20, 10, 311, 241))
        self.columnView_3.setObjectName("columnView_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(200, 30, 111, 22))
        self.comboBox.setObjectName("comboBox")
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setMaxVisibleItems(10)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(200, 270, 111, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setMaxVisibleItems(10)
        self.comboBox_2.setObjectName("comboBox")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.Imagelbl = QtWidgets.QLabel(self.centralwidget)
        self.Imagelbl.setGeometry(QtCore.QRect(30, 110, 128, 128))
        self.Imagelbl.setMaximumSize(QtCore.QSize(200, 200))
        self.Imagelbl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Imagelbl.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Imagelbl.setText("")
        self.Imagelbl.setObjectName("Imagelbl")
        self.Imagelbl_2 = QtWidgets.QLabel(self.centralwidget)
        self.Imagelbl_2.setGeometry(QtCore.QRect(190, 110, 128, 128))
        self.Imagelbl_2.setMaximumSize(QtCore.QSize(200, 200))
        self.Imagelbl_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Imagelbl_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Imagelbl_2.setText("")
        self.Imagelbl_2.setObjectName("Imagelbl_2")
        self.Imagelbl_3 = QtWidgets.QLabel(self.centralwidget)
        self.Imagelbl_3.setGeometry(QtCore.QRect(30, 360, 128, 128))
        self.Imagelbl_3.setMaximumSize(QtCore.QSize(200, 200))
        self.Imagelbl_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Imagelbl_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Imagelbl_3.setText("")
        self.Imagelbl_3.setObjectName("Imagelbl_3")
        self.Imagelbl_4 = QtWidgets.QLabel(self.centralwidget)
        self.Imagelbl_4.setGeometry(QtCore.QRect(190, 360, 128, 128))
        self.Imagelbl_4.setMaximumSize(QtCore.QSize(200, 200))
        self.Imagelbl_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Imagelbl_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Imagelbl_4.setText("")
        self.Imagelbl_4.setObjectName("Imagelbl_4")
        self.BrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseButton.setGeometry(QtCore.QRect(50, 30, 75, 23))
        self.BrowseButton.setObjectName("pushButton")
        self.BrowseButton.setFont(font)
        self.BrowseButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseButton_2.setGeometry(QtCore.QRect(50, 270, 75, 23))
        self.BrowseButton_2.setObjectName("pushButton_2")
        self.BrowseButton_2.setFont(font)
        self.columnView_4 = QtWidgets.QColumnView(self.centralwidget)
        self.columnView_4.setGeometry(QtCore.QRect(370, 10, 311, 241))
        self.columnView_4.setObjectName("columnView_4")
        self.columnView_5 = QtWidgets.QColumnView(self.centralwidget)
        self.columnView_5.setGeometry(QtCore.QRect(370, 260, 311, 241))
        self.columnView_5.setObjectName("columnView_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 320, 113, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        f = QtGui.QFont()
        f.setPointSize(12)
        f.setBold(True)
        f.setWeight(75)
        self.lineEdit_2.setFont(f)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(390, 20, 141, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        m = QtGui.QFont()
        m.setPointSize(11)
        m.setBold(True)
        m.setWeight(75)

        self.lineEdit_3.setFont(m)
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(570, 20, 101, 22))
        self.comboBox_3.setFont(font)
        self.comboBox_3.setMaxVisibleItems(10)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(380, 89, 81, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_5.setFont(font)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(380, 170, 81, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(480, 90, 71, 31))
        self.comboBox_5.setFont(font)
        self.comboBox_5.setMaxVisibleItems(10)
        self.comboBox_5.setObjectName("comboBox")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.lineEdit_6.setFont(font)
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(480, 170, 71, 31))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.setFont(font)
        self.comboBox_6.setMaxVisibleItems(10)
        self.comboBox_6.setObjectName("comboBox")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(560, 100, 111, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setRange(0,10)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setSliderPosition(0)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(560, 180, 111, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_2.setRange(0,10)
        self.horizontalSlider_2.setSingleStep(1)
        self.horizontalSlider_2.setSliderPosition(0)
        self.horizontalSlider_2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_2.setTickInterval(1)
        self.horizontalSlider_2.setTracking(True)
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setGeometry(QtCore.QRect(480, 130, 90, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.setFont(font)
        self.comboBox_7.setMaxVisibleItems(10)
        self.comboBox_7.setObjectName("comboBox")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setGeometry(QtCore.QRect(480, 210, 90, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.setFont(font)
        self.comboBox_8.setMaxVisibleItems(10)
        self.comboBox_8.setObjectName("comboBox")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(30, 70, 113, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        
        
       
        f = QtGui.QFont()
        f.setPointSize(12)
        f.setBold(True)
        f.setWeight(75)
        self.lineEdit_7.setFont(f)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(390, 290, 113, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.setFont(f)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(540, 290, 113, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_8.setFont(f)
        self.Imagelbl_5 = QtWidgets.QLabel(self.centralwidget)
        self.Imagelbl_5.setGeometry(QtCore.QRect(390, 350, 128, 128))
        self.Imagelbl_5.setMaximumSize(QtCore.QSize(200, 200))
        self.Imagelbl_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Imagelbl_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Imagelbl_5.setText("")
        self.Imagelbl_5.setObjectName("Imagelbl_5")
        self.Imagelbl_6 = QtWidgets.QLabel(self.centralwidget)
        self.Imagelbl_6.setGeometry(QtCore.QRect(540, 350, 128, 128))
        self.Imagelbl_6.setMaximumSize(QtCore.QSize(200, 200))
        self.Imagelbl_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Imagelbl_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Imagelbl_6.setText("")
        self.Imagelbl_6.setObjectName("Imagelbl_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BrowseButton.setText(_translate("MainWindow", "Browse"))
        self.BrowseButton_2.setText(_translate("MainWindow", "Browse"))
        self.comboBox.setCurrentText(_translate("MainWindow", "FFT Effects"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Phase"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Imaginary"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Real"))
        self.comboBox_2.setCurrentText(_translate("MainWindow", "FFT Effects"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Phase"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Imaginary"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Real"))
        self.lineEdit_2.setText(_translate("MainWindow","Image Two:"))
        self.lineEdit_7.setText(_translate("MainWindow","Image One:"))
        self.lineEdit_3.setText(_translate("MainWindow","Mixer Output To:"))
        self.comboBox_3.setCurrentText(_translate("MainWindow", "Output"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Output One"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Output Two"))
        self.lineEdit_5.setText(_translate("MainWindow","Comp One:"))
        self.lineEdit_6.setText(_translate("MainWindow","Comp Two:"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Image 1"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Image 2"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Image 1"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Image 2"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Phase"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "Imaginary"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "MagUnitPhase"))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "ImgUnitPhase"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "Real"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "Phase"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "Imaginary"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "Real"))
        self.comboBox_8.setItemText(4, _translate("MainWindow", "MagUnitPhase"))
        self.comboBox_8.setItemText(5, _translate("MainWindow", "ImgUnitPhase"))
        self.lineEdit_8.setText(_translate("MainWindow","Output Two:"))
        self.lineEdit_4.setText(_translate("MainWindow","Output One:"))
        
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
